version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/app/wait-for-it.sh", "elasticsearch:9200", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
